# Generated by Django 5.0.1 on 2024-02-02 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportApp', '0002_myreport_writer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myreport',
            name='writer',
        ),
    ]
